packages:
  - client
  - server
  - docs
  - monitor-agent
  - shared

packageExtensions:
  "@hookform/resolvers@*":
    peerDependencies:
      zod: "*"
    peerDependenciesMeta:
      zod:
        optional: true
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/rate-limit@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
